server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8087/eureka

spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cold?CharsetEncoding=utf8&&Timezone=Asia/Shanghai
    username: root
    password: root