server:
  port: 8087

eureka:
  instance:
    hostname: 0.0.0.0
  client:
    service-url:
      defaultZone: http://127.0.0.1:8087/eureka
    fetch-registry: false
    register-with-eureka: false
spring:
  application:
    name: eureka
