server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8087/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-router
          uri: http://127.0.0.1:8088
          predicates:
            - Path=/user/**

        - id: system-router
          uri: http://127.0.0.1:8089
          predicates:
            - Path=/system/**